services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - back
    env_file:
      - ./properties.env

  be:
    build:
      context: .
      dockerfile: Dockerfile.be
    container_name: kotlin-be
    ports:
      - "8080:8080"
    networks:
      - back
    depends_on:
      - db
    env_file:
      - ./properties.env


volumes:
  db_data:

networks:
  back: