FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=basic_be
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=root

COPY dump-db-basic_be.sql /docker-entrypoint-initdb.d/init.sql

EXPOSE 3306

CMD ["mysqld"]