services:
  db:
    image: kotlin-be-db
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - back

  be:
    image: kotlin-be
    container_name: kotlin-be
    ports:
      - "8080:8080"
    networks:
      - back
    depends_on:
      - db  


volumes:
  db_data:

networks:
  back: